### ISSUE TITLE
Bump ubuntu on CI to 24.04

### ISSUE THREAD

**Issue by alexallmont** [PalamaraLab/threads#59]
Currently github actions are 22.04, but arg-needle-lib is 24.04.

Also update dependabot to pick up docker/actions out of date, e.g. 
```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```
